create table if not exists public.translations (
  id bigint generated by default as identity primary key,
  locale varchar(5) not null,
  key varchar(255) not null,
  value text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Legacy tables may exist without nucleify columns; CREATE above is skipped.
alter table public.translations add column if not exists locale varchar(5);
alter table public.translations add column if not exists key varchar(255);
alter table public.translations add column if not exists value text;
alter table public.translations add column if not exists created_at timestamptz not null default now();
alter table public.translations add column if not exists updated_at timestamptz not null default now();

-- Legacy single-column unique on key breaks multi-locale rows (same key, different locale).
alter table public.translations drop constraint if exists translations_key_key;

create unique index if not exists translations_locale_key_uidx on public.translations (locale, key);

create index if not exists translations_locale_idx on public.translations (locale);
alter table public.translations enable row level security;
drop policy if exists "translations_authenticated_all" on public.translations;
create policy "translations_authenticated_all" on public.translations for all to authenticated using (true) with check (true);
