export const countries = [
  { label: 'Algeria', value: 'algeria' },
  { label: 'Argentina', value: 'argentina' },
  { label: 'Australia', value: 'australia' },
  { label: 'Austria', value: 'austria' },
  { label: 'Bahrain', value: 'bahrain' },
  { label: 'Belgium', value: 'belgium' },
  { label: 'Belize', value: 'belize' },
  { label: 'Bolivia', value: 'bolivia' },
  { label: 'Bosnia and Herzegovina', value: 'bosnia-and-herzegovina' },
  { label: 'Brazil', value: 'brazil' },
  { label: 'Brunei Darussalam', value: 'brunei-darussalam' },
  { label: 'Canada', value: 'canada' },
  { label: 'Caribbean', value: 'caribbean' },
  { label: 'Chile', value: 'chile' },
  { label: 'China', value: 'china' },
  { label: 'Colombia', value: 'colombia' },
  { label: 'Costa Rica', value: 'costa-rica' },
  { label: 'Croatia', value: 'croatia' },
  { label: 'Dominican Republic', value: 'dominican-republic' },
  { label: 'Ecuador', value: 'ecuador' },
  { label: 'Egypt', value: 'egypt' },
  { label: 'El Salvador', value: 'el-salvador' },
  { label: 'France', value: 'france' },
  { label: 'Finland', value: 'finland' },
  { label: 'Germany', value: 'germany' },
  { label: 'Guatemala', value: 'guatemala' },
  { label: 'Honduras', value: 'honduras' },
  { label: 'Hong Kong SAR', value: 'hong-kong-sar' },
  { label: 'India', value: 'india' },
  { label: 'Ireland', value: 'ireland' },
  { label: 'Iraq', value: 'iraq' },
  { label: 'Italy', value: 'italy' },
  { label: 'Jamaica', value: 'jamaica' },
  { label: 'Jordan', value: 'jordan' },
  { label: 'Kuwait', value: 'kuwait' },
  { label: 'Lebanon', value: 'lebanon' },
  { label: 'Libya', value: 'libya' },
  { label: 'Liechtenstein', value: 'liechtenstein' },
  { label: 'Luxembourg', value: 'luxembourg' },
  { label: 'Macau SAR', value: 'macau-sar' },
  { label: 'Malaysia', value: 'malaysia' },
  { label: 'Mexico', value: 'mexico' },
  { label: 'Monaco', value: 'monaco' },
  { label: 'Morocco', value: 'morocco' },
  { label: 'Netherlands', value: 'netherlands' },
  { label: 'New Zealand', value: 'new-zealand' },
  { label: 'Nicaragua', value: 'nicaragua' },
  { label: 'Norway', value: 'norway' },
  { label: 'Oman', value: 'oman' },
  { label: 'Panama', value: 'panama' },
  { label: 'Paraguay', value: 'paraguay' },
  { label: 'Peru', value: 'peru' },
  { label: 'Philippines', value: 'philippines' },
  { label: 'Poland', value: 'poland' },
  { label: 'Portugal', value: 'portugal' },
  { label: 'Puerto Rico', value: 'puerto-rico' },
  { label: 'Qatar', value: 'qatar' },
  { label: 'Saudi Arabia', value: 'saudi-arabia' },
  { label: 'Serbia and Montenegro', value: 'serbia-and-montenegro' },
  { label: 'Singapore', value: 'singapore' },
  { label: 'South Africa', value: 'south-africa' },
  { label: 'Spain', value: 'spain' },
  { label: 'Sweden', value: 'sweden' },
  { label: 'Switzerland', value: 'switzerland' },
  { label: 'Syria', value: 'syria' },
  { label: 'Taiwan', value: 'taiwan' },
  { label: 'Trinidad and Tobago', value: 'trinidad-and-tobago' },
  { label: 'Tunisia', value: 'tunisia' },
  { label: 'U.A.E.', value: 'united-arab-emirates' },
  { label: 'United Kingdom', value: 'united-kingdom' },
  { label: 'United States', value: 'united-states' },
  { label: 'Uruguay', value: 'uruguay' },
  { label: 'Venezuela', value: 'venezuela' },
  { label: 'Yemen', value: 'yemen' },
  { label: 'Zimbabwe', value: 'zimbabwe' },
]
