// @generated by nucleify-compiler
// editable; after edits: pnpm compiler -- import --from=react fixtures/source/button.tsx
// content-hash: 3de2729b96e6
'use client'

import './button.css'

type Props = {
  label?: string
}

function onClick() {
  console.log('clicked')
}

export default function Button({ label = 'Click' }: Props) {
  return (
    <button type="button" className="btn" onClick={onClick}>
      {label}
    </button>
  )
}
