// @generated by nucleify-compiler
// editable; after edits: pnpm compiler -- import --from=react fixtures/source/counter.tsx
// content-hash: d33eb4b830e8
'use client'

import { useState, useMemo } from 'react'

type Props = {
  label?: string
}

export default function Counter({ label = 'Count' }: Props) {
  const [count, setCount] = useState(0)
  const double = useMemo(() => count * 2, [count])

  function onInc() {
    setCount(count + 1)
  }

  return (
    <button type="button" onClick={onInc}>
      {label + ': ' + double}
    </button>
  )
}
