// @generated by nucleify-compiler
// editable; after edits: pnpm compiler -- import --from=react fixtures/source/hello.tsx
// content-hash: cc9a6187662a
'use client'

type Props = {
  title: string
}

export default function Hello({ title }: Props) {
  return <h1 className="hello">{title}</h1>
}
