// @generated by nucleify-compiler
// editable; after edits: pnpm compiler -- import --from=react fixtures/source/list.tsx
// content-hash: 37695630898f
'use client'

type Props = {
  items: unknown
  showEmpty?: boolean
}

export default function List({ items, showEmpty = true }: Props) {
  return (
    <div className="list">
      {showEmpty ? <p>Empty hint visible</p> : <p>No empty hint</p>}
      <ul>
        {items.map((item, i) => (
          <li key={i}>{item}</li>
        ))}
      </ul>
    </div>
  )
}
