// @generated by nucleify-compiler
// editable; after edits: pnpm compiler -- import --from=react fixtures/source/nui_cta.tsx
// content-hash: a17b89c6a8d2
'use client'

type Props = {
  label?: string
  disabled?: boolean
  accent?: string
}

function onClick() {
  console.log('nui-cta')
}

export default function NuiCta({
  label = 'Continue',
  disabled = false,
  accent = '#0ea5e9',
}: Props) {
  return (
    <nui-button
      type="button"
      disabled={disabled}
      aria-label={label}
      style={{ color: accent, gap: '0.5rem' }}
      onClick={onClick}
      suppressHydrationWarning
    >
      <nui-icon
        icon="mdi:rocket-launch-outline"
        aria-hidden="true"
        mode="svg"
        suppressHydrationWarning
      />
      {label}
    </nui-button>
  )
}
