import { createHash } from 'node:crypto'

const VUE_HEADER_RE =
  /^<!--\s*(?:@generated by nucleify-compiler|editable;|content-hash:).*-->\s*\n?/
const CSS_HEADER_RE =
  /^\/\*\s*(?:@generated by nucleify-compiler|content-hash:).*\*\/\s*\n?/
const REACT_HEADER_RE =
  /^\/\/\s*(?:@generated by nucleify-compiler|editable;|content-hash:).*\n?/
const USE_CLIENT_RE = /^'use client'\s*;?\s*\n?/

export type EmitKind = 'vue' | 'react' | 'css'

/** Strip leading generated headers (and React `'use client'`) for hashing / dirty checks. */
export function stripEmitHeaders(body: string, kind: EmitKind): string {
  let rest = body.replace(/^\uFEFF/, '')
  if (kind === 'vue') {
    while (VUE_HEADER_RE.test(rest)) rest = rest.replace(VUE_HEADER_RE, '')
  } else if (kind === 'css') {
    while (CSS_HEADER_RE.test(rest)) rest = rest.replace(CSS_HEADER_RE, '')
  } else {
    while (REACT_HEADER_RE.test(rest)) rest = rest.replace(REACT_HEADER_RE, '')
    rest = rest.replace(USE_CLIENT_RE, '')
  }
  return rest
}

export function normalizeBody(body: string): string {
  return body.replace(/\r\n/g, '\n').trim()
}

export function contentHash(body: string): string {
  return createHash('sha256').update(normalizeBody(body), 'utf8').digest('hex').slice(0, 12)
}

export function hashFromDisk(fileContents: string, kind: EmitKind): { expected?: string; actual: string } {
  const hashLine =
    kind === 'vue'
      ? fileContents.match(/<!--\s*content-hash:\s*([a-f0-9]+)\s*-->/)
      : kind === 'css'
        ? fileContents.match(/\/\*\s*content-hash:\s*([a-f0-9]+)\s*\*\//)
        : fileContents.match(/\/\/\s*content-hash:\s*([a-f0-9]+)/)
  const expected = hashLine?.[1]
  const actual = contentHash(stripEmitHeaders(fileContents, kind))
  return { expected, actual }
}

export function isDirty(fileContents: string, kind: EmitKind): boolean {
  const { expected, actual } = hashFromDisk(fileContents, kind)
  if (!expected) return true
  return expected !== actual
}

export function vueHeader(importHintPath: string, hash: string): string {
  return [
    '<!-- @generated by nucleify-compiler -->',
    `<!-- editable; after edits: pnpm compiler -- import --from=vue ${importHintPath} -->`,
    `<!-- content-hash: ${hash} -->`,
    '',
  ].join('\n')
}

export function cssHeader(hash: string): string {
  return [
    '/* @generated by nucleify-compiler */',
    `/* content-hash: ${hash} */`,
    '',
  ].join('\n')
}

export function reactHeader(importHintPath: string, hash: string): string {
  return [
    '// @generated by nucleify-compiler',
    `// editable; after edits: pnpm compiler -- import --from=react ${importHintPath}`,
    `// content-hash: ${hash}`,
    "'use client'",
    '',
  ].join('\n')
}
