import { existsSync } from 'node:fs'
import { basename, dirname, join, resolve } from 'node:path'

export type EmitSibling = 'vue' | 'react' | 'css'

export function emitBaseName(sourcePath: string): string {
  return basename(sourcePath).replace(/\.nuc\.tsx$/, '')
}

export function nucPathFromEmit(emitPath: string): string {
  const dir = dirname(emitPath)
  const base = basename(emitPath).replace(/\.(vue|tsx|css)$/, '')
  return join(dir, `${base}.nuc.tsx`)
}

export function siblingPath(nucPath: string, kind: EmitSibling): string {
  const dir = dirname(nucPath)
  const base = emitBaseName(nucPath)
  if (kind === 'vue') return join(dir, `${base}.vue`)
  if (kind === 'react') return join(dir, `${base}.tsx`)
  return join(dir, `${base}.css`)
}

export function resolveImportPath(cwd: string, inputPath: string): {
  componentPath: string
  kind: 'vue' | 'react' | 'css'
} {
  const abs = resolve(cwd, inputPath)
  if (abs.endsWith('.nuc.tsx')) {
    throw new Error('import: pass .vue / .tsx / .css emit path, not *.nuc.tsx (use build for authoring)')
  }
  if (abs.endsWith('.vue')) return { componentPath: abs, kind: 'vue' }
  if (abs.endsWith('.tsx')) return { componentPath: abs, kind: 'react' }
  if (abs.endsWith('.css')) {
    const base = basename(abs, '.css')
    const dir = dirname(abs)
    const vue = join(dir, `${base}.vue`)
    const tsx = join(dir, `${base}.tsx`)
    if (existsSync(vue)) return { componentPath: vue, kind: 'vue' }
    if (existsSync(tsx)) return { componentPath: tsx, kind: 'react' }
    throw new Error(`import: no sibling .vue/.tsx for ${inputPath}`)
  }
  throw new Error(`import: expected .vue, .tsx, or .css path, got ${inputPath}`)
}

export function inferComponentName(base: string): string {
  return base
    .split(/[_-]/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
}

export function isGeneratedEmit(contents: string, kind: EmitSibling): boolean {
  if (kind === 'vue') return contents.includes('<!-- @generated by nucleify-compiler -->')
  if (kind === 'react') return contents.includes('// @generated by nucleify-compiler')
  return contents.includes('/* @generated by nucleify-compiler */')
}
