-- If public.user_colors already exists without nucleify columns, "CREATE TABLE IF NOT EXISTS (...)"
-- is skipped — policies must not reference user_id until columns exist.

create table if not exists public.user_colors (
  id bigint generated by default as identity primary key
);

alter table public.user_colors add column if not exists user_id uuid references auth.users (id) on delete cascade;
alter table public.user_colors add column if not exists name text;
alter table public.user_colors add column if not exists value text;
alter table public.user_colors add column if not exists new boolean not null default false;
alter table public.user_colors add column if not exists is_new boolean not null default false;
alter table public.user_colors add column if not exists created_at timestamptz not null default now();
alter table public.user_colors add column if not exists updated_at timestamptz not null default now();

create unique index if not exists user_colors_user_id_name_uidx on public.user_colors (user_id, name);

alter table public.user_colors enable row level security;

drop policy if exists "user_colors_select_own" on public.user_colors;
create policy "user_colors_select_own"
on public.user_colors
for select
using (auth.uid() = user_id);

drop policy if exists "user_colors_upsert_own" on public.user_colors;
create policy "user_colors_upsert_own"
on public.user_colors
for insert
with check (auth.uid() = user_id);

drop policy if exists "user_colors_update_own" on public.user_colors;
create policy "user_colors_update_own"
on public.user_colors
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "user_colors_delete_own" on public.user_colors;
create policy "user_colors_delete_own"
on public.user_colors
for delete
using (auth.uid() = user_id);
