create table if not exists public.system_colors (
  id bigint generated by default as identity primary key,
  name text not null unique,
  value text not null,
  new boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.system_colors enable row level security;

drop policy if exists "system_colors_select_public" on public.system_colors;
create policy "system_colors_select_public"
on public.system_colors
for select
to anon, authenticated
using (true);

alter table public.system_colors
  add column if not exists new boolean not null default false;
