-- user_colors DDL + legacy RLS: 20260430000002_user_colors.sql

create table if not exists public.system_colors (
  id bigint generated by default as identity primary key,
  name text not null unique,
  value text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.user_colors enable row level security;
alter table public.system_colors enable row level security;

drop policy if exists "user_colors_authenticated_all" on public.user_colors;
create policy "user_colors_authenticated_all" on public.user_colors for all to authenticated using (true) with check (true);

drop policy if exists "system_colors_authenticated_read" on public.system_colors;
create policy "system_colors_authenticated_read" on public.system_colors for select to authenticated using (true);
