#!/usr/bin/env bash
# Merges all module SQL under shared_modules/*/supabase/{migrations,factories,seeders}
# into supabase/.temp/merged_*.sql (same ordering as apply-module-*.sh).
# Usage: bash .config/bash/merge-module-supabase-sql.sh [migrations|factories|seeders|all]

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd -- "$SCRIPT_DIR/../.." && pwd)"
PKG_DIR="$ROOT_DIR/web"
TARGET="${1:-all}"
if [[ "$TARGET" != "migrations" && "$TARGET" != "factories" && "$TARGET" != "seeders" && "$TARGET" != "all" ]]; then
  echo "Usage: bash .config/bash/merge-module-supabase-sql.sh [migrations|factories|seeders|all]"
  exit 1
fi

OUT_DIR="$ROOT_DIR/supabase/.temp"
mkdir -p "$OUT_DIR"

write_placeholder() {
  local out="$1"
  local note="$2"
  {
    echo "-- $note (no matching .sql files)"
    echo "select 1;"
  } > "$out"
}

append_sorted_stdin_to_out() {
  local out="$1"
  while IFS='|' read -r base_name module_name src; do
    [[ -n "${src:-}" ]] || continue
    [[ -f "$src" ]] || continue
    rel_path="${src#$ROOT_DIR/}"
    {
      echo ""
      echo "-- >>> $rel_path [$module_name]"
      cat "$src"
      echo ""
      echo "-- <<< $rel_path"
    } >> "$out"
  done
}

merge_migrations() {
  local out="$OUT_DIR/merged_migrations.sql"
  shopt -s nullglob
  local module_sources=( "$ROOT_DIR"/shared_modules/*/supabase/migrations/*.sql )
  if [[ ${#module_sources[@]} -eq 0 ]]; then
    write_placeholder "$out" "merged_migrations"
    echo "Wrote $out (placeholder, no sources)"
    return 0
  fi
  local tmp_list
  tmp_list="$(mktemp)"
  for src in "${module_sources[@]}"; do
    local module_name base_name
    module_name="$(basename "$(dirname "$(dirname "$(dirname "$src")")")")"
    base_name="$(basename "$src")"
    printf '%s|%s|%s\n' "$base_name" "$module_name" "$src" >> "$tmp_list"
  done
  {
    echo "-- merged_migrations.sql (autogenerated)"
    echo "-- source: shared_modules/*/supabase/migrations/*.sql sorted by filename"
    echo "-- rebuild: bash .config/bash/merge-module-supabase-sql.sh migrations"
    echo ""
  } > "$out"
  sort "$tmp_list" | append_sorted_stdin_to_out "$out"
  rm -f "$tmp_list"
  echo "Wrote $out"
}

merge_factories() {
  local out="$OUT_DIR/merged_factories.sql"
  shopt -s nullglob
  local sources=( "$ROOT_DIR"/shared_modules/*/supabase/factories/*.sql )
  if [[ ${#sources[@]} -eq 0 ]]; then
    write_placeholder "$out" "merged_factories"
    echo "Wrote $out (placeholder, no sources)"
    return 0
  fi
  local tmp_list
  tmp_list="$(mktemp)"
  for src in "${sources[@]}"; do
    local module_name base_name
    module_name="$(basename "$(dirname "$(dirname "$(dirname "$src")")")")"
    base_name="$(basename "$src")"
    printf '%s|%s|%s\n' "$base_name" "$module_name" "$src" >> "$tmp_list"
  done
  {
    echo "-- merged_factories.sql (autogenerated)"
    echo "-- source: shared_modules/*/supabase/factories/*.sql sorted by filename"
    echo "-- rebuild: bash .config/bash/merge-module-supabase-sql.sh factories"
    echo ""
  } > "$out"
  sort "$tmp_list" | append_sorted_stdin_to_out "$out"
  rm -f "$tmp_list"
  echo "Wrote $out"
}

merge_seeders() {
  local out="$OUT_DIR/merged_seeders.sql"
  local tmp_list
  tmp_list="$(mktemp)"
  local found_any=0
  if [[ -f "$ROOT_DIR/shared_modules/nuc_modules/scripts/generate-seeder.mjs" ]]; then
    (cd "$ROOT_DIR" && node shared_modules/nuc_modules/scripts/generate-seeder.mjs) || {
      rm -f "$tmp_list"
      exit 1
    }
  fi
  shopt -s nullglob
  for module_dir in "$ROOT_DIR"/shared_modules/*; do
    [[ -d "$module_dir" ]] || continue
    local module_name
    module_name="$(basename "$module_dir")"
    local module_seeder="$module_dir/supabase/seeders/module_seeder.sql"
    if [[ -f "$module_seeder" ]]; then
      found_any=1
      printf '00000000000000_module_seeder.sql|%s|%s\n' "$module_name" "$module_seeder" >> "$tmp_list"
      continue
    fi
    local legacy_seeders=( "$module_dir"/supabase/seeders/*.sql )
    if [[ ${#legacy_seeders[@]} -gt 0 ]]; then
      found_any=1
      for src in "${legacy_seeders[@]}"; do
        local base_name
        base_name="$(basename "$src")"
        printf '%s|%s|%s\n' "$base_name" "$module_name" "$src" >> "$tmp_list"
      done
    fi
  done
  if [[ "$found_any" -eq 0 ]]; then
    write_placeholder "$out" "merged_seeders"
    rm -f "$tmp_list"
    echo "Wrote $out (placeholder, no sources)"
    return 0
  fi
  {
    echo "-- merged_seeders.sql (autogenerated)"
    echo "-- source: shared_modules/*/supabase/seeders (module_seeder.sql first per module when present)"
    echo "-- rebuild: bash .config/bash/merge-module-supabase-sql.sh seeders"
    echo ""
  } > "$out"
  sort "$tmp_list" | append_sorted_stdin_to_out "$out"
  rm -f "$tmp_list"
  echo "Wrote $out"
}

case "$TARGET" in
  migrations) merge_migrations ;;
  factories) merge_factories ;;
  seeders) merge_seeders ;;
  all)
    merge_migrations
    merge_factories
    merge_seeders
    ;;
esac
