import { describe, expect, it } from 'vitest'
import { irEventToReact, irEventToVue, reactEventToIr } from '../src/adapters/events'
import { toReactClassName, toVueClassAttr } from '../src/adapters/class-name'
import { contentHash, isDirty, normalizeBody, stripEmitHeaders } from '../src/sync/fingerprint'

describe('adapters', () => {
  it('maps IR events to Vue / React', () => {
    expect(irEventToVue('click')).toBe('@click')
    expect(irEventToReact('click')).toBe('onClick')
    expect(reactEventToIr('onClick')).toBe('click')
  })

  it('maps class / className', () => {
    expect(toVueClassAttr('className')).toBe('class')
    expect(toVueClassAttr('class')).toBe('class')
    expect(toReactClassName('class')).toBe('className')
  })
})

describe('fingerprint', () => {
  it('hashes normalized body', () => {
    expect(contentHash('a\n')).toBe(contentHash('a'))
    expect(contentHash('a')).not.toBe(contentHash('b'))
  })

  it('detects dirty when hash missing or mismatched', () => {
    const body = normalizeBody('<script setup lang="ts"></script>\n<template><div /></template>')
    const hash = contentHash(body)
    const clean = `<!-- @generated by nucleify-compiler -->\n<!-- editable; after edits: pnpm compiler -- import --from=vue x -->\n<!-- content-hash: ${hash} -->\n${body}\n`
    expect(isDirty(clean, 'vue')).toBe(false)
    expect(isDirty(body, 'vue')).toBe(true)
    expect(stripEmitHeaders(clean, 'vue').trim()).toBe(body)
  })
})
