<!-- @generated by nucleify-compiler -->
<!-- editable; after edits: pnpm compiler -- import --from=vue fixtures/source/button.vue -->
<!-- content-hash: e41d445de88b -->
<script setup lang="ts">
import './button.css'

const props = withDefaults(
  defineProps<{
    label?: string
  }>(),
  {
    label: 'Click',
  }
)

function onClick() {
  console.log('clicked')
}
</script>

<template>
  <button type="button" class="btn" @click="onClick">
    {{ props.label }}
  </button>
</template>
