<!-- @generated by nucleify-compiler -->
<!-- editable; after edits: pnpm compiler -- import --from=vue fixtures/source/counter.vue -->
<!-- content-hash: 570b729186fd -->
<script setup lang="ts">
import { ref, computed } from 'vue'

const props = withDefaults(
  defineProps<{
    label?: string
  }>(),
  {
    label: 'Count',
  }
)

const count = ref(0)

const double = computed(() => count.value * 2)

function onInc() {
  count.value = count.value + 1
}
</script>

<template>
  <button type="button" @click="onInc">
    {{ ((props.label + ': ') + double) }}
  </button>
</template>
