<!-- @generated by nucleify-compiler -->
<!-- editable; after edits: pnpm compiler -- import --from=vue fixtures/source/hello.vue -->
<!-- content-hash: 7b37af766060 -->
<script setup lang="ts">
const props = defineProps<{
  title: string
}>()
</script>

<template>
  <h1 class="hello">
    {{ props.title }}
  </h1>
</template>
