<!-- @generated by nucleify-compiler -->
<!-- editable; after edits: pnpm compiler -- import --from=vue fixtures/source/list.vue -->
<!-- content-hash: 4d8e3cf13298 -->
<script setup lang="ts">
const props = withDefaults(
  defineProps<{
    items: unknown
    showEmpty?: boolean
  }>(),
  {
    showEmpty: true,
  }
)
</script>

<template>
  <div class="list">
    <p v-if="props.showEmpty">Empty hint visible</p>
    <p v-else>No empty hint</p>
    <ul>
      <li v-for="(item, i) in props.items" :key="i">
        {{ item }}
      </li>
    </ul>
  </div>
</template>
