<!-- @generated by nucleify-compiler -->
<!-- editable; after edits: pnpm compiler -- import --from=vue fixtures/source/nui_cta.vue -->
<!-- content-hash: a2f23579413d -->
<script setup lang="ts">
const props = withDefaults(
  defineProps<{
    label?: string
    disabled?: boolean
    accent?: string
  }>(),
  {
    label: 'Continue',
    disabled: false,
    accent: '#0ea5e9',
  }
)

function onClick() {
  console.log('nui-cta')
}
</script>

<template>
  <nui-button
    type="button"
    :disabled="props.disabled"
    :aria-label="props.label"
    :style="{ color: props.accent, gap: '0.5rem' }"
    @click="onClick"
  >
    <nui-icon icon="mdi:rocket-launch-outline" aria-hidden="true" />
    {{ props.label }}
  </nui-button>
</template>
